server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  banner:
    location: classpath:banner.txt

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none # Production uchun 'none' yoki 'validate' eng to'g'ri
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Ilovaning maxsus sozlamalari
application:
  jwt:
    secret: ${APPLICATION_JWT_SECRET}
    access-token-expiration: ${APPLICATION_JWT_ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${APPLICATION_JWT_REFRESH_TOKEN_EXPIRATION}
  minio:
    endpoint: ${APPLICATION_MINIO_ENDPOINT}
    access-key: ${APPLICATION_MINIO_ACCESS_KEY}
    secret-key: ${APPLICATION_MINIO_SECRET_KEY}
    buckets:
      - images
      - other
      - icons
  telegram:
    bot:
      token: ${APPLICATION_TELEGRAM_BOT_TOKEN}
      username: ${APPLICATION_TELEGRAM_BOT_USERNAME}
      webhook-path: ${APPLICATION_TELEGRAM_BOT_WEBHOOK_PATH}
      chat-id: ${APPLICATION_TELEGRAM_CHAT_ID}
      channel-id: ${APPLICATION_TELEGRAM_CHANNEL_ID}