server:
  port: 8080

spring:

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

  banner:
    location: classpath:banner.txt

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://central_postgres_db:5432/weather
    username: postgres
    password: 2503

  liquibase:
    analytics-enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: 176.57.188.165
      port: 6379
      password: 2503
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: parol
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    uz:
      pdp:
        online_education:
          service:
            GenerateService=DEBUG:
#    root: WARN
#    org.springframework.web: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.type.descriptor.sql: TRACE
#    com.example.your.app: DEBUG

application:
  jwt:
    secret: ${JWT_SECRET_KEY}

    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}

    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
  cache:
    temporary-process-ttl-seconds: ${CACHE_TIME}

  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN}
      username: ${TELEGRAM_BOT_USERNAME}
      channel-id: ${TELEGRAM_BOT_CHANNEL}
  server_ip: ${SERVER_IP}
  domain: ${MY_DOMAIN}